version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
image:
  - Visual Studio 2019
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    package_version: '{version}'
nuget:
  account_feed: false
  project_feed: false
before_build:
- cmd: nuget restore
- ps: >-
    ls C:\projects\lightblue
    
    dotnet restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy: off